services:
  - type: web
    name: nanny-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    rootDir: frontend
    staticPublishPath: build
